name: Release AnimalTamer plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up JDK 15
        id: get_tag
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create release
        id: create_release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: build/libs/AnimalTamer.jar
          release_name  : Release ${{ steps.vars.outputs.tag }}
          body: |
            #### Plugin and Source release ${{ steps.vars.outputs.tag }}
          prerelease: false